---
# Install security tools

- name: Install security tools (macOS)
  ansible.builtin.command: brew install {{ macos_security_tools | join(' ') }}
  register: brew_install_security
  changed_when: "'already installed' not in brew_install_security.stderr"
  failed_when: brew_install_security.rc != 0 and 'already installed' not in brew_install_security.stderr
  become: false
  when: ansible_os_family == "Darwin"

- name: Install security tools (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ debian_security_tools }}"
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Install security tools (RedHat/CentOS)
  ansible.builtin.package:
    name: "{{ redhat_security_tools }}"
    state: present
  become: true
  when: ansible_os_family == "RedHat"
